variables:
  PLUGIN: 'enrol_gwpayments'
  PATHNAME: 'enrol/gwpayments'
  REPOURL: 'https://github.com/sebsoftnl/moodle-enrol_gwpayments'

include:
  - project: 'sebsoft/open-source/gitlab'
    file: '/opensource-plugin/opensource-plugin-405+.yml'
    ref: main
